const db = window.itAntSupabase;
const page = document.querySelector('#invoice-page');
const money = value => `${Number(value || 0).toLocaleString('sr-RS', { minimumFractionDigits: 2, maximumFractionDigits: 2 })} RSD`;
const date = value => { const d = new Date(value); return `${String(d.getDate()).padStart(2, '0')}.${String(d.getMonth() + 1).padStart(2, '0')}.${d.getFullYear()}`; };
const esc = value => String(value || '').replace(/[&<>"']/g, char => ({ '&':'&amp;', '<':'&lt;', '>':'&gt;', '"':'&quot;', "'":'&#39;' }[char]));
const vatLabel = item => item.vat_treatment === 'exempt_right' ? 'Oslobođeno + pravo' : item.vat_treatment === 'exempt_no' ? 'Oslobođeno bez prava' : `${Number(item.vat_rate || 0)}%`;

async function load() {
  const id = new URLSearchParams(location.search).get('id');
  if (!id) { page.innerHTML = '<p class="error">Račun nije izabran.</p>'; return; }
  const { data: invoice, error } = await db.from('invoices').select('id,number,status,issue_date,due_date,subtotal,total,vat_amount,tax_regime,notes,clients(name,pib,mb,address,invoice_email),invoice_items(description,quantity,unit_price,vat_rate,vat_treatment,vat_amount)').eq('id', id).single();
  if (error || !invoice) { page.innerHTML = `<p class="error">Račun nije moguće učitati: ${esc(error?.message)}</p>`; return; }
  const { data: membership } = await db.from('company_users').select('companies(name,pib,tax_regime,vat_number)').limit(1).single();
  const company = membership?.companies || {};
  const items = invoice.invoice_items || [];
  page.innerHTML = `<div class="toolbar"><button type="button" onclick="window.print()">Štampaj / Sačuvaj kao PDF</button></div><section class="sheet"><header class="invoice-head"><div class="issuer"><img class="logo" src="Logo-Transparent.png" alt="IT ANT"><h1>${esc(company.name || 'Preduzeće')}</h1><p>PIB: ${esc(company.pib || '—')}</p><p>${company.tax_regime === 'books_vat' ? `PDV broj: ${esc(company.vat_number || '—')}` : 'Nije u sistemu PDV'}</p></div><div class="invoice-title"><h2>Račun</h2><p><strong>Broj:</strong> ${esc(invoice.number)}</p><p><strong>Datum izdavanja:</strong> ${date(invoice.issue_date)}</p>${invoice.due_date ? `<p><strong>Rok plaćanja:</strong> ${date(invoice.due_date)}</p>` : ''}</div></header><section class="parties"><div><p class="party-label">Izdavalac</p><div class="issuer"><p>${esc(company.name || '—')}</p><p>PIB: ${esc(company.pib || '—')}</p><p>${company.tax_regime === 'books_vat' ? `PDV broj: ${esc(company.vat_number || '—')}` : 'Nije u sistemu PDV'}</p></div></div><div class="recipient"><p class="party-label">Kupac</p><h3>${esc(invoice.clients?.name || '—')}</h3><p>PIB: ${esc(invoice.clients?.pib || '—')}</p><p>MB: ${esc(invoice.clients?.mb || '—')}</p><p>Adresa: ${esc(invoice.clients?.address || '—')}</p></div></section><table class="items"><thead><tr><th>Opis usluge</th><th class="num">Količina</th><th class="num">Cena</th><th>PDV</th><th class="num">Ukupno</th></tr></thead><tbody>${items.map(item => `<tr><td>${esc(item.description)}</td><td class="num">${item.quantity}</td><td class="num">${money(item.unit_price)}</td><td>${company.tax_regime === 'books_vat' ? vatLabel(item) : '—'}</td><td class="num">${money(Number(item.quantity) * Number(item.unit_price) + Number(item.vat_amount || 0))}</td></tr>`).join('')}</tbody></table><table class="totals"><tr><td>Osnovica:</td><td>${money(invoice.subtotal ?? invoice.total)}</td></tr>${company.tax_regime === 'books_vat' ? `<tr><td>PDV:</td><td>${money(invoice.vat_amount)}</td></tr>` : ''}<tr><td>Za uplatu:</td><td>${money(invoice.total)}</td></tr></table>${invoice.notes ? `<p class="notes"><strong>Napomena:</strong> ${esc(invoice.notes)}</p>` : ''}<footer class="footer">Dokument je generisan iz aplikacije IT ANT Poslovanje. Status računa: ${invoice.status === 'paid' ? 'Plaćen' : invoice.status === 'cancelled' ? 'Storniran' : 'Čeka uplatu'}</footer></section>`;
}
load();
